### ISSUE TITLE
Вопрос про лицензию проекта

### ISSUE THREAD

**Issue by bonkboykz** [thelastpolaris/anti-corona-crm#80]
Привет!
У меня возник вопрос про лицензию данного проекта. В корне лежит файл с текстом оригинальной MIT лицензиий, но в README репо есть дополнения, которые его модифицируют и, как мне кажется, уже не делают проект совместимым с лицензией

**Comment by thelastpolaris** [comment]
Привет!
Спасибо за интерес к проекту. Ты имеешь в виду требования по копирайту или использование других библиотек?

**Comment by bonkboykz** [comment]
Спасибо за актуальный проект, да еще и в опен сорсе :)
Меня забеспокоил вот этот момент:
```
Вы всегда должны указывать следующую информацию, если собираетесь рассказать о данном проекте в новостях, соц. сетях, использовать его или делать fork проекта. ...
Отсутствие данной информации при упоминании и использовании данного проекта, а также искаженная подача данной информации будет рассматриваться как нарушение лицензии.
```
Я думаю такое дополнение уже не считается стандартной MIT лицензией и нужно указать, что это не обычная MIT лицензия или выбрать другую, более строгую и которая позволяет такие модификации

**Comment by thelastpolaris** [comment]
Даже если MIT не самая строгая лицензия, это не значит, что можно забывать про копирайт :)

Выдержка из файла LICENSE.md:

«A short and simple permissive license with conditions only requiring preservation of copyright and license notices.»

Ты можешь форкать проект и развивать его сам, просто не забудь указать оригинальных авторов - это единственное требование MIT лицензии, что не делает ее строгой :)

**Comment by bonkboykz** [comment]
Я имел в виду [дополнение из README](https://github.com/thelastpolaris/anti-corona-crm#legal-disclaimer--%D0%BB%D0%B8%D1%86%D0%B5%D0%BD%D0%B7%D0%B8%D1%8F).
Уверен, что обязательство указывать дополнительную информацию при определенных действиях для соблюдения лицензии не дает использовать MIT :)

**Comment by thelastpolaris** [comment]
Ну давай для начала определим что такое «определенные действия» и «дополнительная информация» с легальной точки зрения. 

Если под «дополнительными действиями» ты подразумеваешь упоминания проекта, то да, это немного серая зона и условным СМИ пофигу на МИТ лицензию.

Если «дополнительные действия» это форк или использование кода, а «дополнительная информация» это копирайт, который я требую при совершении этих «дополнительных действий», то я не вижу где здесь падает compliance with MIT license.

Если я что-то не понимаю, то прошу простить и объяснить подробнее :)

**Comment by thelastpolaris** [comment]
Или ты про то что Copyright должен быть во всех файлах отдельно?

**Comment by bonkboykz** [comment]
Если по простому, сейчас лицензия, чтобы она считалась валидной, заставляет делать что-то помимо включения текста копирайта и лицензии в копии кода, что уже делает ее не MIT compliant 🤔

**Comment by thelastpolaris** [comment]
Я понял, да, думаю ты прав - я обновил файл README.md

Скажу честно, я добавил этот момент совсем недавно, потому что у меня был не очень хороший опыт и в тот момент я боялся, что с проектом могут сделать кое-что не хорошее. В любом случае, если мы говорим о копирайте, то это то, что я указал в лицензии. В будущем я могу обновить копирайт, но пока так. А та информация, которую я прошу упоминать, это credit всем тем людям, которые участвовали в проекте. Вот уже три месяца эпидемиологи со всего Казахстана помогают мне идеями и фидбеком, без них это была бы просто груда ненужного кода :)

**Comment by bonkboykz** [comment]
Конечно понимаю, это большая проделанная работа :)
Я думаю любое честное СМИ или делевелопер не откажет в соотвествущем credit'е, а нечеткая лицензия может отпугнуть.
Прочитал, думаю теперь все как надо, спасибо!

**Comment by thelastpolaris** [comment]
Спасибо за добрые слова :)

Эх, если бы так было все хорошо, с указанием авторов у нас проблемы. Но по поводу лицензии согласен.

Спасибо за интерес к проекту :)
